#ifndef NETWORKCONFIG_H
#define NETWORKCONFIG_H

#define DEFAULT_PORT "27015"
#define DEFAULT_ADDRESS "localhost"

#define NETWORK_BUFLEN_DEFAULT 512
#define NETWORK_BUFLEN NETWORK_BUFLEN_DEFAULT

#define NETWORK_PASSCODE 0xDEADBEEF
#define NETWORK_VERSION 1

#endif // NETWORKCONFIG_H
